### ISSUE TITLE
internal todo

### ISSUE THREAD

**Issue by DanielRuf** [amsul/pickadate.js#1047]
* [ ] enable projects and boards
* [ ] add issue template
* [ ] create codepen for issue template
* [ ] add pullrequest template
* [ ] use [all contributors](https://www.npmjs.com/package/all-contributors-cli)
* [ ] move to org
* [ ] npm publishing rights
* [ ] use some translation platform?
...

**Comment by amsul** [comment]
@DanielRuf I would also love to see [all-contributors](https://github.com/kentcdodds/all-contributors) be recognized :)
